# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "WTM Alicante 2018"
email: "wtmalicante@gmail.com"
description: "WTM es una iniciativa promovida por google para dar visibilidad a las mujeres en el mundo de la tecnolog√≠a"
baseurl: ""
url: "https://wtmalicante.github.io"
permalink: "/blog/:title"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "WTM Alicante"
organizerAlternateName: "Women Techmakers Alicante"
organizerDescription: ""
organizerEmail: "wtmalicante@gmail.com"
organizerLogo: "/img/seo/organizer-logo-1.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@gdgAlicante"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus-1.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter-2.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook-1.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/taller/", text: "Taller"}
bottomNavigationLinks:
 - {link: "https://www.meetup.com/es-ES/GDG-Alicante/events/248135541/", text: "¬°Quiero asistir al evento!"}
rightNavigationButtons:
 - {link: "https://www.meetup.com/es-ES/GDG-Alicante/events/248135541/", text: "¬°Quiero asistir al evento!"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "WTM Alicante 2018 <br/> <typeout>"
eventDate: "S√°bado 14 de Abril"
typeoutTextValues: '"", "Tecnolog√≠a", "Mujeres", "Makers", "IWD"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://www.meetup.com/es-ES/GDG-Alicante/events/248135541/", text: "¬°Quiero asistir al evento!"}

# About Block
aboutTitle: "Women Techmakers Alicante"
aboutBlock:
- {title: "Conference", text: '<b>Women Techmakers</b> es una iniciativa liderada por Google para dar visibilidad a las mujeres en el aÃÅmbito de la tecnologiÃÅa. Con motivo del<b> DiÃÅa Internacional de la Mujer</b>, se promueven diferentes eventos alrededor del mundo con el objetivo de dar a conocer el trabajo y el conocimiento de las mujeres en el sector teÃÅcnico.<br/>Desde <a href="https://www.meetup.com/es-ES/GDG-Alicante/">GDG Alicante</a> (Google Developer Group) queremos aportar nuestro granito de arena para promover la tecnologiÃÅa entre las mujeres y joÃÅvenes de nuestra ciudad.</b> Este evento seraÃÅ<b> gratuito y abierto a toda la comunidad </b>y tendraÃÅ como <b>protagonista a la <u>tecnologiÃÅa</u> y a las <u>mujeres</u>.</b> üë©‚Äçüíª </br> <a href="https://www.meetup.com/es-ES/GDG-Alicante/events/248135541/?eventId=248135541"> Ap√∫ntate al evento AQU√ç</a>'}
#- {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 11
rockstarSpeakersTitle: "Nuestras ponentes"
#rockstarSpeakersText: "¬°Atentos a nuevas confirmaciones pr√≥ximamente!"
#rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Localizaci√≥n"
eventLocationName: "Sal√≥n de actos del Club INFORMACI√ìN"
eventLocationLink: "http://www.clubinformacion.com/"
eventStreetAddress: "Avda. Doctor Rico, 17"
eventAddressLocality: "Alicante"
eventAddressLocalityRegion: "Alicante"
eventPostalCode: "03005"
eventAddressCountry: "Espa√±a"
eventStartTime: "2018-04-14T09:00"
eventDoorTime: "09:00"
eventEndTime: "2018-04-14T18:00"
eventPlaceCoordinates: "38.3543511, -0.4994115"
mapCenterCoordinates: "38.3542102, -0.498333"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Lugar"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Sal√≥n de actos del Club Informaci√≥n"
venueFeatures: ["Aforo de 220 personas", "Av. Dr. Rico, 17, 03005 Alicante"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGAlicante", icon: "twitter"}
 #- {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/es-ES/GDG-Alicante/", text: "Meetup GDG Alicante"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:wtmalicante@gmail.com", text: "wtmalicante@gmail.com"}
 -
 # title: "FAQ"
 # links:
 #  - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Taller Apolo: Viajando al espacio"
aboutUs: "L@s ni√±@s durante este taller descubriraÃÅn las tecnologiÃÅas creativas, aprenderaÃÅn un poco maÃÅs de la historia de la ciencia, la tecnologiÃÅa y las mujeres que han formado parte de ella, y sobre todo ¬°se lo pasaraÃÅn en grande! se conviertan en ayudantes de Margaret Hamilton, la mujer que lideroÃÅ la navegacioÃÅn on-board del programa Espacial Apolo. A traveÃÅs de su historia y gracias a las tecnologiÃÅas creativas Scratch y Makey Makey los participantes alcanzaraÃÅn el objetivo de su misioÃÅn: llegar al espacio exterior."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn‚Äôt use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
